### ISSUE TITLE
Proposition d'ajout d'un test pour un fichier vide

### ISSUE THREAD

**Issue by JulesBourgine** [anisg/fillit_checker#4]
Salut !
J'ai remarqué que parmi tes tests, il n'y en a pas qui teste un fichier vide.
Ca peut etre une source facile de segfault si le cas n'est pas géré donc je me dis que ca serait intéressant de l'ajouter !

**Comment by anisg** [comment]
C'est vrai, ça servira sans doute à d'autres, j'ai ajouté ton test. Sympa merci :)
