### ISSUE TITLE
Test à rajouter dans le fillit checker

### ISSUE THREAD

**Issue by Failte21** [anisg/fillit_checker#5]
Mon programme passe tous les tests du file checker, pourtant il considère comme juste un fichier qui contient un tetriminos dans cette configuration :
. . . .
##.#
. . .#
. . . .

**Comment by anisg** [comment]
Ha, Il y a souvent des erreurs bizarres auquel on s'attend pas... Merci! j'ai mis ton test en place.

**Comment by bricewge** [comment]
Cette issue devrait être fermée, le test a été ajouté avec b2c358e7b170cd88ed9f1b0d961e2636543b8af1.
